import os


ARTIFACTS_DIR = os.path.join(os.path.dirname(__file__), "artifacts")
DEFAULT_RANDOM_SEED = 42
DEFAULT_EMBED_DIM = 128
DEFAULT_NUM_FILTERS = 100
DEFAULT_FILTER_SIZES = [3, 4, 5]
DEFAULT_DROPOUT = 0.5
DEFAULT_MAX_LEN = 50
DEFAULT_MAX_VOCAB_SIZE = 20000
DEFAULT_BATCH_SIZE = 64
DEFAULT_EPOCHS = 10
DEFAULT_LR = 1e-3
DEFAULT_MIN_FREQ = 1
